# SonarQube Local Configuration — ControlFit Frontend
sonar.projectKey=controfit-frontend
sonar.projectName=ControlFit Frontend
sonar.host.url=http://localhost:9000

# Fuente
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts

# Lenguaje
sonar.language=ts

# Cobertura (generada por Angular CLI + karma)
sonar.javascript.lcov.reportPaths=coverage/controlfit-front/lcov.info

# Exclusiones
sonar.exclusions=src/environments/**,src/**/*.spec.ts,node_modules/**,dist/**
sonar.coverage.exclusions=src/**/*.spec.ts,src/environments/**,src/main.ts,src/app/app.config.ts,src/app/app.routes.ts
